name: Release to Crates.io

on:
  release:
    types:
      - published

jobs:
  publish:
    steps:
      runs-on: ubuntu-latest

      - uses: actions/checkout@v1
      - run: cargo login ${CRATES_IO_TOKEN}
        env:
            CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
      - run: cargo publish
